# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46356374a705a44181d62cb48f5d1882c220c8890fccf2e78c274013cf15bc995fdb4f77d5e6fdebd9712a38f385af4b9c9e4e9df1da3e6bbcf0a8dbee652377

test:
  secret_key_base: 6963e5280ecd4ffe4f767ad1a2586add1bdeb50b23e82013b0ede87682fad269b3ebd4cc6cedca9c8451b782b67486b87ea8f8720e8f7fbb59be1c7de6ab05b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
